jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - run:
          name: Install Git & SSH
          command: |
            pacman -Sy --noconfirm git openssh
      - run:
          name: Checkout Code
          command: |
            git config --global user.email "i@margatroid.xyz" # TODO: Change the email
            git config --global user.name "CircleCI"
            echo "Host *" >> /etc/ssh/ssh_config
            echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config
            echo "    UserKnownHostsFile=/dev/null" >> /etc/ssh/ssh_config
            git clone git@github.com:Enter-tainer/CITeX.git --depth=1 # TODO: Change the link
      - run:
          name: Install and configure dependencies
          command: |
            pacman -S --noconfirm texlive-most texlive-langchinese fish adobe-source-han-serif-cn-fonts
      - run:
          name: Build LaTeX
          command: |
            cd LaTeXDocs
            fish ./build.fish
            fish ./clean.fish
      - run:
          name: Push to GitHub
          command: |
            cd LaTeXDocs
            fish ./deploy.fish
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
